// Curated puzzle database
// Each puzzle has 7 unique letters, with one center letter that must be used
export const puzzles = [
  {
    id: 1,
    letters: ['G', 'R', 'I', 'N', 'D', 'E', 'A'],
    centerLetter: 'A',
    validWords: [
      'adage', 'added', 'addend', 'addenda', 'adder', 'adding', 'adenine', 'aedine',
      'aerie', 'aeried', 'aerier', 'again', 'agar', 'aged', 'agee', 'ageing',
      'agenda', 'agene', 'ager', 'agger', 'aggie', 'aggrade', 'aggraded', 'aggrading',
      'agin', 'aging', 'aginner', 'agrarian', 'agree', 'agreed', 'agreeing', 'agria',
      'aide', 'aided', 'aider', 'aiding', 'aired', 'airer', 'airier', 'airing',
      'airn', 'anear', 'aneared', 'anearing', 'anergia', 'anga', 'angaria', 'anger',
      'angered', 'angering', 'angina', 'angrier', 'anna', 'araneid', 'area', 'areae',
      'arena', 'arginine', 'aria', 'arid', 'arider', 'arraign', 'arraigned', 'arraigning',
      'arrange', 'arranged', 'arranger', 'arranging', 'arrear', 'arrearage', 'dada', 'dagga',
      'dagger', 'daggered', 'daggering', 'dander', 'dandered', 'dandering', 'dandier', 'dang',
      'danged', 'danger', 'dangered', 'dangering', 'danging', 'dare', 'dared', 'darer',
      'daring', 'darn', 'darned', 'darneder', 'darner', 'darning', 'dead', 'deaden',
      'deadened', 'deadener', 'deadening', 'deader', 'deair', 'deaired', 'deairing', 'dean',
      'deaned', 'deaning', 'dear', 'dearer', 'dearie', 'degage', 'degrade', 'degraded',
      'degrader', 'degrading', 'denarii', 'deraign', 'deraigned', 'deraigning', 'derange', 'deranged',
      'deranging', 'dinar', 'drag', 'dragee', 'dragged', 'dragger', 'draggier', 'dragging',
      'drain', 'drainage', 'drained', 'drainer', 'draining', 'dread', 'dreaded', 'dreading',
      'drear', 'drearier', 'eager', 'eagerer', 'eagre', 'eared', 'earing', 'earn',
      'earned', 'earner', 'earning', 'earring', 'egad', 'eggar', 'endanger', 'endangered',
      'endangering', 'endear', 'endeared', 'endearing', 'engage', 'engaged', 'engager', 'engaging',
      'engrain', 'engrained', 'engraining', 'ennead', 'enrage', 'enraged', 'enraging', 'errand',
      'gadarene', 'gadded', 'gadder', 'gaddi', 'gadding', 'gadi', 'gadid', 'gaed',
      'gaeing', 'gaen', 'gaga', 'gage', 'gaged', 'gager', 'gagged', 'gagger',
      'gagging', 'gaging', 'gain', 'gained', 'gainer', 'gaining', 'gander', 'gandered',
      'gandering', 'gane', 'gang', 'ganged', 'ganger', 'ganging', 'gangrene', 'gangrened',
      'gangrening', 'garage', 'garaged', 'garaging', 'garden', 'gardened', 'gardener', 'gardenia',
      'gardening', 'garner', 'garnered', 'garnering', 'garni', 'garred', 'garring', 'gear',
      'geared', 'gearing', 'genera', 'gerardia', 'giga', 'gnar', 'gnarr', 'gnarred',
      'gnarring', 'grad', 'grade', 'graded', 'grader', 'gradin', 'gradine', 'grading',
      'grain', 'grained', 'grainer', 'grainier', 'graining', 'gran', 'grana', 'grand',
      'grandad', 'granddad', 'grandee', 'grander', 'grange', 'granger', 'grannie', 'greengage',
      'gregarine', 'grenade', 'grenadier', 'grenadine', 'idea', 'inane', 'inaner', 'ingrain',
      'ingrained', 'ingraining', 'inia', 'irade', 'naan', 'nada', 'nadir', 'nagana',
      'nagged', 'nagger', 'naggier', 'nagging', 'naiad', 'naira', 'nana', 'nandin',
      'nandina', 'nannie', 'nard', 'nardine', 'narine', 'near', 'neared', 'nearer',
      'nearing', 'niggard', 'niggarded', 'niggarding', 'radar', 'radded', 'radding', 'radian',
      'radii', 'raga', 'rage', 'raged', 'ragee', 'ragged', 'raggeder', 'raggee',
      'ragging', 'ragi', 'raging', 'raia', 'raid', 'raided', 'raider', 'raiding',
      'rain', 'rained', 'rainier', 'raining', 'rand', 'randan', 'randier', 'ranee',
      'rang', 'range', 'ranged', 'ranger', 'rangier', 'ranging', 'rani', 'ranid',
      'rare', 'rared', 'rarer', 'raring', 'read', 'readd', 'readded', 'readding',
      'reader', 'readied', 'readier', 'reading', 'reagin', 'rear', 'reared', 'rearer',
      'rearing', 'rearrange', 'rearranged', 'rearranging', 'redan', 'redear', 'redia', 'rediae',
      'reearn', 'reearned', 'reearning', 'reengage', 'reengaged', 'reengaging', 'regain', 'regained',
      'regainer', 'regaining', 'regard', 'regarded', 'regarding', 'regear', 'regeared', 'regearing',
      'reggae', 'regina', 'reginae', 'regna', 'regrade', 'regraded', 'regrading', 'renegade',
      'renegaded', 'renegading', 'reran', 'reread', 'rereading',
    ],
    pangrams: ['arraigned', 'daggering', 'dandering', 'dangering', 'deairing', 'degrading', 'deraign', 'deraigned', 'deraigning', 'deranging', 'drainage', 'dreading', 'endangering', 'endearing', 'engrained', 'gandering', 'gardenia', 'gardening', 'gradine', 'grained', 'grenadier', 'grenadine', 'ingrained', 'niggarded', 'readding', 'reading', 'regained', 'regarding', 'regrading', 'renegading', 'rereading']
  },
  {
    id: 2,
    letters: ['T', 'H', 'O', 'U', 'G', 'R', 'N'],
    centerLetter: 'N',
    validWords: [
      'gong', 'goon', 'gorgon', 'grunt', 'hognut', 'hong', 'honor', 'honour',
      'horn', 'hung', 'hunh', 'hunt', 'nogg', 'nontruth', 'noon', 'north',
      'notturno', 'nought', 'noun', 'onto', 'outgun', 'outhunt', 'outrun', 'outrung',
      'outturn', 'rung', 'runout', 'runt', 'thong', 'thorn', 'thoron', 'throng',
      'tong', 'toon', 'torn', 'trogon', 'tung', 'turn', 'turnout', 'ungot',
      'unhung', 'unhurt', 'unroot', 'unrough', 'unthought', 'unto', 'untorn', 'untruth',
    ],
    pangrams: []
  },
  {
    id: 3,
    letters: ['C', 'L', 'O', 'U', 'D', 'Y', 'R'],
    centerLetter: 'O',
    validWords: [
      'clod', 'cloddy', 'cloud', 'cloudy', 'clour', 'cloy', 'coco', 'cold',
      'coldly', 'colly', 'color', 'colour', 'coly', 'coocoo', 'cool', 'coolly',
      'cooly', 'cord', 'corduroy', 'corody', 'corrody', 'cory', 'could', 'coyly',
      'croc', 'cruor', 'cyclo', 'dodo', 'doll', 'dolly', 'dolor', 'dolour',
      'dooly', 'door', 'dorr', 'dory', 'dour', 'dourly', 'doyly', 'droll',
      'drolly', 'drool', 'duro', 'duroc', 'loco', 'loll', 'lolly', 'lord',
      'lordly', 'lorry', 'lory', 'loud', 'loudly', 'lour', 'loury', 'occur',
      'oddly', 'odor', 'odour', 'odyl', 'oldy', 'ordo', 'rococo', 'roll',
      'rood', 'your',
    ],
    pangrams: []
  },
  {
    id: 4,
    letters: ['S', 'P', 'I', 'R', 'T', 'E', 'N'],
    centerLetter: 'E',
    validWords: [
      'eerie', 'eerier', 'eeriest', 'eeriness', 'eerinesses', 'einstein', 'einsteins', 'entente',
      'ententes', 'enter', 'enterer', 'enterers', 'enteritis', 'enteritises', 'enterprise', 'enterpriser',
      'enterprisers', 'enterprises', 'enters', 'entire', 'entireness', 'entirenesses', 'entires', 'entireties',
      'entities', 'entree', 'entrees', 'entries', 'epee', 'epeeist', 'epeeists', 'epees',
      'erepsin', 'erepsins', 'erne', 'ernes', 'erns', 'errs', 'erses', 'erst',
      'eserine', 'eserines', 'eses', 'espies', 'esprit', 'esprits', 'esses', 'ester',
      'esters', 'estrin', 'estrins', 'eterne', 'eternise', 'eternises', 'eternities', 'inept',
      'ineptness', 'ineptnesses', 'inert', 'inertness', 'inertnesses', 'inerts', 'inner', 'inners',
      'insentient', 'insert', 'inserter', 'inserters', 'inserts', 'inset', 'insets', 'insetter',
      'insetters', 'insistent', 'insister', 'insisters', 'inspire', 'inspirer', 'inspirers', 'inspires',
      'instep', 'insteps', 'intense', 'intenseness', 'intensenesses', 'intenser', 'intensest', 'intensities',
      'intent', 'intentness', 'intentnesses', 'intents', 'inter', 'interest', 'interests', 'intern',
      'interne', 'internee', 'internees', 'internes', 'internist', 'internists', 'interns', 'interpret',
      'interpreter', 'interpreters', 'interprets', 'inters', 'intersperse', 'intersperses', 'intertie', 'interties',
      'intestine', 'intestines', 'intine', 'intines', 'ires', 'irises', 'iritises', 'issei',
      'isseis', 'neep', 'neeps', 'neist', 'nene', 'nereis', 'nerts', 'ness',
      'nesses', 'nest', 'nester', 'nesters', 'nests', 'nets', 'nett', 'netter',
      'netters', 'nettier', 'nettiest', 'netts', 'nine', 'ninepin', 'ninepins', 'nines',
      'nineteen', 'nineteens', 'nineties', 'ninnies', 'nipper', 'nippers', 'nippier', 'nippiest',
      'nippiness', 'nippinesses', 'nisei', 'niseis', 'nite', 'niter', 'niterie', 'niteries',
      'niters', 'nites', 'nitre', 'nitres', 'nitrite', 'nitrites', 'nittier', 'nittiest',
      'peen', 'peens', 'peep', 'peeper', 'peepers', 'peeps', 'peer', 'peeress',
      'peeresses', 'peerie', 'peeries', 'peers', 'pees', 'pein', 'peins', 'peise',
      'peises', 'penes', 'penis', 'penises', 'penitent', 'penitents', 'penne', 'penner',
      'penners', 'penni', 'pennies', 'pennine', 'pennines', 'pennis', 'pens', 'pensee',
      'pensees', 'penster', 'pensters', 'pent', 'pentene', 'pentenes', 'pepper', 'pepperer',
      'pepperers', 'pepperiness', 'pepperinesses', 'peppers', 'peppertree', 'peppertrees', 'peppier', 'peppiest',
      'peppiness', 'peppinesses', 'peps', 'pepsin', 'pepsine', 'pepsines', 'pepsins', 'peri',
      'peripeties', 'peripter', 'peripters', 'peris', 'perpent', 'perpents', 'perries', 'perse',
      'perses', 'persist', 'persistent', 'persister', 'persisters', 'persists', 'perspire', 'perspires',
      'pert', 'perter', 'pertest', 'pertinent', 'pertness', 'pertnesses', 'pest', 'pester',
      'pesterer', 'pesterers', 'pesters', 'pestier', 'pestiest', 'pests', 'peter', 'peters',
      'petit', 'petite', 'petiteness', 'petitenesses', 'petites', 'pets', 'petter', 'petters',
      'petti', 'pettier', 'pettiest', 'pettiness', 'pettinesses', 'pier', 'piers', 'pies',
      'pieties', 'pietist', 'pietists', 'pine', 'pinene', 'pinenes', 'pineries', 'pines',
      'pinier', 'piniest', 'pinite', 'pinites', 'pinner', 'pinners', 'pinnies', 'pinsetter',
      'pinsetters', 'pinstripe', 'pinstripes', 'pipe', 'piper', 'piperine', 'piperines', 'pipers',
      'pipes', 'pipet', 'pipets', 'pipette', 'pipettes', 'pipier', 'pipiest', 'pipiness',
      'pipinesses', 'pisser', 'pissers', 'pisses', 'piste', 'pistes', 'pitier', 'pitiers',
      'pities', 'pree', 'preen', 'preener', 'preeners', 'preens', 'prees', 'prep',
      'prepense', 'preppie', 'preppier', 'preppies', 'preppiest', 'preppiness', 'preppinesses', 'preprint',
      'preprints', 'preps', 'prerinse', 'prerinses', 'prese', 'present', 'presentee', 'presentees',
      'presenter', 'presenters', 'presentient', 'presentist', 'presentness', 'presentnesses', 'presents', 'preset',
      'presets', 'press', 'presser', 'pressers', 'presses', 'prest', 'prester', 'presters',
      'prestress', 'prestresses', 'prests', 'preteen', 'preteens', 'pretense', 'pretenses', 'preterit',
      'preterite', 'preterites', 'preterits', 'pretest', 'pretests', 'prettier', 'pretties', 'prettiest',
      'prettiness', 'prettinesses', 'prier', 'priers', 'pries', 'priest', 'priestess', 'priestesses',
      'priests', 'printer', 'printeries', 'printers', 'prise', 'prisere', 'priseres', 'prises',
      'prisses', 'prissier', 'prissies', 'prissiest', 'prissiness', 'prissinesses', 'pristine', 'pterin',
      'pterins', 'reenter', 'reenters', 'reentries', 'rees', 'reest', 'reests', 'rein',
      'reins', 'reinsert', 'reinserts', 'reinspire', 'reinspires', 'reinter', 'reinterpret', 'reinterprets',
      'reinters', 'reis', 'renest', 'renests', 'renin', 'renins', 'renitent', 'rennet',
      'rennets', 'rennin', 'rennins', 'rent', 'rente', 'renter', 'renters', 'rentes',
      'rentier', 'rentiers', 'rents', 'repent', 'repenter', 'repenters', 'repents', 'repin',
      'repine', 'repiner', 'repiners', 'repines', 'repins', 'repp', 'repps', 'represent',
      'representer', 'representers', 'represents', 'repress', 'represses', 'reprint', 'reprinter', 'reprinters',
      'reprints', 'reprise', 'reprises', 'reps', 'rerise', 'rerisen', 'rerises', 'resee',
      'reseen', 'resees', 'resent', 'resents', 'reserpine', 'reserpines', 'reset', 'resets',
      'resetter', 'resetters', 'resin', 'resins', 'resist', 'resister', 'resisters', 'resists',
      'resite', 'resites', 'respire', 'respires', 'respite', 'respites', 'rest', 'rester',
      'resters', 'restress', 'restresses', 'rests', 'rete', 'retene', 'retenes', 'retest',
      'retests', 'retie', 'reties', 'retine', 'retinene', 'retinenes', 'retines', 'retinite',
      'retinites', 'retinitis', 'retint', 'retints', 'retire', 'retiree', 'retirees', 'retirer',
      'retirers', 'retires', 'retries', 'rets', 'rinse', 'rinser', 'rinsers', 'rinses',
      'ripe', 'ripen', 'ripener', 'ripeners', 'ripeness', 'ripenesses', 'ripens', 'riper',
      'ripes', 'ripest', 'ripieni', 'ripper', 'rippers', 'rise', 'risen', 'riser',
      'risers', 'rises', 'rite', 'rites', 'ritter', 'ritters', 'seen', 'seep',
      'seepier', 'seepiest', 'seeps', 'seer', 'seeress', 'seeresses', 'seers', 'sees',
      'seine', 'seiner', 'seiners', 'seines', 'seis', 'seise', 'seiser', 'seisers',
      'seises', 'seisin', 'seisins', 'sene', 'seniti', 'sennet', 'sennets', 'sennit',
      'sennits', 'sense', 'senses', 'sensitise', 'sensitises', 'sent', 'sente', 'senti',
      'sentient', 'sentients', 'sentries', 'sepses', 'sepsis', 'sept', 'septet', 'septets',
      'septette', 'septettes', 'septs', 'sere', 'serein', 'sereins', 'serene', 'sereneness',
      'serenenesses', 'serener', 'serenes', 'serenest', 'serenities', 'serer', 'seres', 'serest',
      'series', 'serin', 'serine', 'serines', 'serins', 'serpent', 'serpentine', 'serpentines',
      'serpents', 'serries', 'sers', 'sestet', 'sestets', 'sestine', 'sestines', 'sets',
      'sett', 'settee', 'settees', 'setter', 'setters', 'setts', 'sienite', 'sienites',
      'sine', 'sines', 'sinister', 'sinisterness', 'sinisternesses', 'sinner', 'sinners', 'sinter',
      'sinters', 'sipe', 'sipes', 'sipper', 'sippers', 'sippet', 'sippets', 'sire',
      'siree', 'sirees', 'siren', 'sirens', 'sires', 'sirree', 'sirrees', 'sises',
      'sissier', 'sissies', 'sissiest', 'sister', 'sisters', 'site', 'sites', 'sitten',
      'sitter', 'sitters', 'sneer', 'sneerer', 'sneerers', 'sneers', 'snipe', 'sniper',
      'snipers', 'snipes', 'snipper', 'snippers', 'snippet', 'snippetier', 'snippetiest', 'snippets',
      'snippier', 'snippiest', 'speer', 'speers', 'speir', 'speirs', 'speise', 'speises',
      'speiss', 'speisses', 'spense', 'spenses', 'spent', 'spier', 'spiers', 'spies',
      'spine', 'spines', 'spinet', 'spinets', 'spinier', 'spiniest', 'spininess', 'spininesses',
      'spinner', 'spinneret', 'spinnerets', 'spinnerette', 'spinnerettes', 'spinneries', 'spinners', 'spinnies',
      'spinster', 'spinsters', 'spire', 'spires', 'spirier', 'spiriest', 'spite', 'spites',
      'spitter', 'spitters', 'spree', 'sprees', 'sprent', 'sprier', 'spriest', 'sprinter',
      'sprinters', 'sprite', 'sprites', 'steep', 'steepen', 'steepens', 'steeper', 'steepers',
      'steepest', 'steepness', 'steepnesses', 'steeps', 'steer', 'steerer', 'steerers', 'steers',
      'stein', 'steins', 'step', 'steppe', 'stepper', 'steppers', 'steppes', 'steps',
      'stepsister', 'stepsisters', 'stere', 'steres', 'stern', 'sterner', 'sternest', 'sternite',
      'sternites', 'sternness', 'sternnesses', 'sterns', 'stet', 'stets', 'sties', 'stinter',
      'stinters', 'stipe', 'stipes', 'stipites', 'stirpes', 'stirrer', 'stirrers', 'street',
      'streets', 'strep', 'streps', 'stress', 'stresses', 'strette', 'stretti', 'stripe',
      'striper', 'stripers', 'stripes', 'stripier', 'stripiest', 'stripper', 'strippers', 'teen',
      'teener', 'teeners', 'teenier', 'teeniest', 'teens', 'teensier', 'teensiest', 'teentsier',
      'teentsiest', 'teepee', 'teepees', 'tees', 'teeter', 'teeters', 'tenet', 'tenets',
      'tenner', 'tenners', 'tennies', 'tennis', 'tennises', 'tennist', 'tennists', 'tenpin',
      'tenpins', 'tens', 'tense', 'tenseness', 'tensenesses', 'tenser', 'tenses', 'tensest',
      'tensities', 'tent', 'tenter', 'tenters', 'tentie', 'tentier', 'tentiest', 'tents',
      'tepee', 'tepees', 'terete', 'tern', 'terne', 'ternes', 'terns', 'terpene',
      'terpenes', 'terreen', 'terreens', 'terrene', 'terrenes', 'terret', 'terrets', 'terrier',
      'terriers', 'terries', 'terrine', 'terrines', 'territ', 'territs', 'terse', 'terseness',
      'tersenesses', 'terser', 'tersest', 'test', 'testee', 'testees', 'tester', 'testers',
      'testes', 'testier', 'testiest', 'testiness', 'testinesses', 'testis', 'tests', 'tets',
      'tetter', 'tetters', 'tiepin', 'tiepins', 'tier', 'tiers', 'ties', 'tine',
      'tines', 'tinier', 'tiniest', 'tininess', 'tininesses', 'tinner', 'tinners', 'tinnier',
      'tinniest', 'tinniness', 'tinninesses', 'tinter', 'tinters', 'tipper', 'tippers', 'tippet',
      'tippets', 'tippier', 'tippiest', 'tipsier', 'tipsiest', 'tipsiness', 'tipsinesses', 'tipster',
      'tipsters', 'tire', 'tires', 'titer', 'titers', 'titre', 'titres', 'titter',
      'titterer', 'titterers', 'titters', 'tittie', 'titties', 'tree', 'treen', 'treens',
      'trees', 'tress', 'tresses', 'tressier', 'tressiest', 'tret', 'trets', 'triene',
      'trienes', 'triens', 'trientes', 'trier', 'triers', 'tries', 'trine', 'trines',
      'trinities', 'tripe', 'tripes', 'tripper', 'trippers', 'trippet', 'trippets', 'trippier',
      'trippiest', 'triste', 'trite', 'triteness', 'tritenesses', 'triter', 'tritest', 'tsetse',
      'tsetses',
    ],
    pangrams: ['enterprise', 'enterpriser', 'enterprisers', 'enterprises', 'interpreters', 'interprets', 'intersperse', 'intersperses', 'persistent', 'pinsetter', 'pinsetters', 'pinstripe', 'pinstripes', 'preprints', 'presentient', 'presentist', 'prettiness', 'prettinesses', 'printeries', 'printers', 'pristine', 'pterins', 'reinterprets', 'reprinters', 'reprints', 'serpentine', 'serpentines', 'snippetier', 'spinneret', 'spinnerets', 'spinnerette', 'spinnerettes', 'spinster', 'spinsters', 'sprinter', 'sprinters']
  },
  {
    id: 5,
    letters: ['M', 'A', 'K', 'I', 'N', 'G', 'W'],
    centerLetter: 'A',
    validWords: [
      'again', 'agama', 'agin', 'aging', 'agma', 'aiming', 'akin', 'amain',
      'amia', 'amiga', 'amin', 'amnia', 'anga', 'angina', 'anima', 'animi',
      'anna', 'awaking', 'awing', 'awning', 'gaga', 'gagging', 'gaging', 'gagman',
      'gain', 'gaining', 'gama', 'gamin', 'gaming', 'gamma', 'gamming', 'gang',
      'ganging', 'gawk', 'gawking', 'giga', 'gnaw', 'gnawing', 'gnawn', 'imaging',
      'imagining', 'imam', 'inia', 'kaiak', 'kain', 'kaka', 'kaki', 'kamaaina',
      'kami', 'kamik', 'kana', 'kiang', 'kina', 'magi', 'magian', 'magma',
      'maim', 'maiming', 'main', 'making', 'mama', 'mamma', 'mana', 'managing',
      'manakin', 'manana', 'mania', 'manikin', 'manna', 'mannan', 'mannikin', 'manning',
      'mawing', 'mawn', 'mina', 'minima', 'naan', 'nagana', 'nagging', 'naming',
      'nana', 'nankin', 'wagging', 'waging', 'wain', 'wakiki', 'waking', 'wangan',
      'wanigan', 'waning', 'wannigan', 'wanning', 'wigan', 'wigwag', 'wigwagging', 'wigwam',
      'wingman',
    ],
    pangrams: []
  },
  {
    id: 6,
    letters: ['F', 'L', 'O', 'W', 'E', 'R', 'S'],
    centerLetter: 'O',
    validWords: [
      'eros', 'erose', 'eroses', 'error', 'errorless', 'errors', 'felloe', 'felloes',
      'fellow', 'fellows', 'feoff', 'feoffee', 'feoffees', 'feoffer', 'feoffers', 'feoffor',
      'feoffors', 'feoffs', 'floe', 'floes', 'floor', 'floorer', 'floorers', 'floors',
      'floss', 'flosses', 'flow', 'flower', 'flowerer', 'flowerers', 'flowerless', 'flowers',
      'flows', 'foes', 'folles', 'follow', 'follower', 'followers', 'follows', 'fool',
      'fools', 'fore', 'forefeel', 'forefeels', 'fores', 'foresee', 'foreseer', 'foreseers',
      'foresees', 'foreswore', 'forswore', 'foss', 'fosse', 'fosses', 'fowl', 'fowler',
      'fowlers', 'fowls', 'froe', 'froes', 'frore', 'frow', 'frows', 'lessor',
      'lessors', 'loess', 'loesses', 'loll', 'loller', 'lollers', 'lolls', 'loof',
      'loofs', 'loos', 'loose', 'looser', 'looses', 'lore', 'lores', 'lose',
      'losel', 'losels', 'loser', 'losers', 'loses', 'loss', 'losses', 'lowe',
      'lower', 'lowers', 'lowes', 'lows', 'lowse', 'offer', 'offerer', 'offerers',
      'offeror', 'offerors', 'offers', 'offs', 'oleo', 'oleos', 'oles', 'oloroso',
      'olorosos', 'ores', 'orle', 'orles', 'oses', 'owes', 'owls', 'owse',
      'reflow', 'reflower', 'reflowers', 'reflows', 'reoffer', 'reoffers', 'reroll', 'reroller',
      'rerollers', 'rerolls', 'reroof', 'reroofs', 'rerose', 'resole', 'resoles', 'resow',
      'resows', 'roes', 'role', 'roles', 'rolf', 'rolfer', 'rolfers', 'rolfs',
      'roll', 'roller', 'rollers', 'rolls', 'roof', 'roofer', 'roofers', 'roofless',
      'roofs', 'roose', 'rooser', 'roosers', 'rooses', 'rose', 'roselle', 'roselles',
      'roses', 'rowel', 'rowels', 'rower', 'rowers', 'rows', 'serow', 'serows',
      'sloe', 'sloes', 'slow', 'slower', 'slows', 'sole', 'soleless', 'soles',
      'solo', 'solos', 'sols', 'sore', 'sorel', 'sorels', 'sorer', 'sores',
      'soroses', 'sorrel', 'sorrels', 'sorrow', 'sorrower', 'sorrowers', 'sorrows', 'sower',
      'sowers', 'sows', 'swore', 'werewolf', 'werwolf', 'woes', 'wolf', 'wolfer',
      'wolfers', 'wolfs', 'wooer', 'wooers', 'woof', 'woofer', 'woofers', 'woofs',
      'wool', 'wooler', 'woolers', 'woolfell', 'woolfells', 'wools', 'woos', 'wore',
      'worse', 'worser', 'worses', 'wows', 'wowser', 'wowsers',
    ],
    pangrams: ['flowerers', 'flowerless', 'flowers', 'followers', 'fowlers', 'reflowers', 'reflows', 'wolfers']
  },
  {
    id: 7,
    letters: ['B', 'R', 'I', 'G', 'H', 'T', 'L'],
    centerLetter: 'I',
    validWords: [
      'bibb', 'bight', 'bill', 'birl', 'birr', 'birth', 'birthright', 'bitt',
      'blight', 'brig', 'bright', 'brill', 'brit', 'britt', 'ghibli', 'gill',
      'gilt', 'girl', 'girt', 'girth', 'glib', 'grig', 'grigri', 'grill',
      'grit', 'grith', 'high', 'highlight', 'hight', 'highth', 'hili', 'hill',
      'hilt', 'libri', 'light', 'lighttight', 'lilt', 'liri', 'right', 'rill',
      'thigh', 'thill', 'thir', 'thirl', 'thrill', 'tight', 'till', 'tilt',
      'tilth', 'tirl', 'titbit', 'titi', 'trig', 'trill',
    ],
    pangrams: []
  },
  {
    id: 8,
    letters: ['C', 'H', 'A', 'N', 'G', 'E', 'S'],
    centerLetter: 'A',
    validWords: [
      'aahs', 'access', 'accesses', 'aces', 'ache', 'achene', 'achenes', 'aches',
      'acne', 'acnes', 'agas', 'agee', 'agene', 'agenes', 'ageneses', 'ages',
      'agha', 'aghas', 'anageneses', 'anas', 'anes', 'anga', 'angas', 'anna',
      'annas', 'ansa', 'ansae', 'asana', 'asanas', 'asceses', 'asea', 'ashcan',
      'ashcans', 'ashen', 'ashes', 'asses', 'assess', 'assesses', 'caca', 'cacas',
      'cache', 'caches', 'caeca', 'cage', 'cages', 'cancan', 'cancans', 'cancha',
      'canchas', 'cane', 'canes', 'canna', 'cannas', 'cans', 'casa', 'casas',
      'case', 'casease', 'caseases', 'cases', 'cash', 'cashes', 'cease', 'ceases',
      'ceca', 'chance', 'chances', 'chang', 'change', 'changes', 'changs', 'chase',
      'chases', 'chasse', 'chasses', 'each', 'ease', 'eases', 'encage', 'encages',
      'encase', 'encases', 'encash', 'encashes', 'enchase', 'enchases', 'engage', 'engages',
      'enhance', 'enhances', 'gaen', 'gaes', 'gaga', 'gage', 'gages', 'gags',
      'ganache', 'ganaches', 'gane', 'gang', 'gangs', 'gases', 'gash', 'gashes',
      'gasses', 'gnash', 'gnashes', 'haen', 'haes', 'hags', 'haha', 'hahas',
      'hahs', 'hance', 'hances', 'hang', 'hangs', 'hansa', 'hansas', 'hanse',
      'hanses', 'hash', 'hasheesh', 'hasheeshes', 'hashes', 'henna', 'hennas', 'naan',
      'naans', 'nachas', 'naches', 'nagana', 'naganas', 'nags', 'nana', 'nanas',
      'nance', 'nances', 'nans', 'nascence', 'nascences', 'sacs', 'saga', 'saganash',
      'saganashes', 'sagas', 'sage', 'sageness', 'sagenesses', 'sages', 'sags', 'sane',
      'saneness', 'sanenesses', 'sanes', 'sang', 'sanga', 'sangas', 'sangh', 'sanghs',
      'sans', 'sash', 'sashes', 'sass', 'sasses', 'scag', 'scags', 'scan',
      'scans', 'scena', 'scenas', 'seance', 'seances', 'seas', 'seneca', 'senecas',
      'senega', 'senegas', 'senna', 'sennas', 'sensa', 'shag', 'shags', 'shah',
      'shahs', 'shea', 'sheas', 'snag', 'snags', 'snash', 'snashes',
    ],
    pangrams: ['changes', 'ganaches']
  },
  {
    id: 9,
    letters: ['P', 'L', 'A', 'Y', 'E', 'R', 'S'],
    centerLetter: 'L',
    validWords: [
      'aals', 'alae', 'alar', 'alary', 'alas', 'alee', 'ales', 'allay',
      'allayer', 'allayers', 'allays', 'allee', 'allees', 'allele', 'alleles', 'alley',
      'alleys', 'alls', 'ally', 'allyl', 'allyls', 'alps', 'appal', 'appall',
      'appalls', 'appals', 'apparel', 'apparels', 'appeal', 'appealer', 'appealers', 'appeals',
      'appel', 'appellee', 'appellees', 'appels', 'apple', 'apples', 'apply', 'areal',
      'areally', 'arles', 'arrayal', 'arrayals', 'aryl', 'aryls', 'asleep', 'asyla',
      'earl', 'earlap', 'earlaps', 'earless', 'earls', 'early', 'easel', 'easels',
      'eels', 'eely', 'elapse', 'elapses', 'ells', 'else', 'eyeless', 'lall',
      'lalls', 'lapel', 'lapels', 'lapper', 'lappers', 'laps', 'lapse', 'lapser',
      'lapsers', 'lapses', 'laree', 'larees', 'lares', 'lars', 'lase', 'laser',
      'lasers', 'lases', 'lass', 'lasses', 'layer', 'layers', 'lays', 'leal',
      'leally', 'leap', 'leaper', 'leapers', 'leaps', 'lear', 'lears', 'leary',
      'leas', 'lease', 'leaser', 'leasers', 'leases', 'leer', 'leers', 'leery',
      'lees', 'leper', 'lepers', 'less', 'lessee', 'lessees', 'lesser', 'leys',
      'lyase', 'lyases', 'lyes', 'lyre', 'lyres', 'lyse', 'lyses', 'lyssa',
      'lyssas', 'paella', 'paellas', 'pale', 'palea', 'paleae', 'paleal', 'palely',
      'paler', 'pales', 'pall', 'palls', 'pally', 'palp', 'palpal', 'palps',
      'pals', 'palsy', 'paly', 'papal', 'papally', 'paperless', 'papyral', 'parallel',
      'parallels', 'paralyse', 'paralyses', 'parlay', 'parlays', 'parle', 'parles', 'parley',
      'parleyer', 'parleyers', 'parleys', 'parral', 'parrals', 'parrel', 'parrels', 'parsley',
      'parsleys', 'passel', 'passels', 'passless', 'peal', 'peals', 'pearl', 'pearler',
      'pearlers', 'pearls', 'pearly', 'peel', 'peeler', 'peelers', 'peels', 'peerless',
      'peerlessly', 'pele', 'peles', 'pepla', 'play', 'playa', 'playas', 'player',
      'players', 'playless', 'plays', 'plea', 'pleas', 'please', 'pleaser', 'pleasers',
      'pleases', 'plyer', 'plyers', 'prerelease', 'prereleases', 'presale', 'presell', 'presells',
      'presleep', 'psylla', 'psyllas', 'rale', 'rales', 'rally', 'rallye', 'rallyes',
      'rappel', 'rappels', 'rarely', 'rassle', 'rassles', 'rayless', 'real', 'realer',
      'reales', 'really', 'reals', 'reapply', 'reel', 'reeler', 'reelers', 'reels',
      'relapse', 'relapser', 'relapsers', 'relapses', 'relay', 'relays', 'release', 'releaser',
      'releasers', 'releases', 'rely', 'repeal', 'repealer', 'repealers', 'repeals', 'repel',
      'repeller', 'repellers', 'repels', 'replay', 'replays', 'reply', 'rerelease', 'rereleases',
      'resale', 'resales', 'reseal', 'reseals', 'resell', 'reseller', 'resellers', 'resells',
      'respell', 'respells', 'salal', 'salals', 'salary', 'sale', 'salep', 'saleps',
      'sales', 'sall', 'sally', 'salp', 'salpa', 'salpae', 'salpas', 'salps',
      'sals', 'salsa', 'salsas', 'sapless', 'seal', 'sealer', 'sealers', 'sealery',
      'seals', 'seel', 'seels', 'seely', 'sell', 'selle', 'seller', 'sellers',
      'selles', 'sells', 'sels', 'sepal', 'sepals', 'seral', 'slap', 'slapper',
      'slappers', 'slaps', 'slay', 'slayer', 'slayers', 'slays', 'sleep', 'sleeper',
      'sleepers', 'sleepless', 'sleeplessly', 'sleeps', 'sleepy', 'slyer', 'slyly', 'slype',
      'slypes', 'spale', 'spales', 'spall', 'spaller', 'spallers', 'spalls', 'sparely',
      'sparsely', 'speel', 'speels', 'spell', 'speller', 'spellers', 'spells', 'splay',
      'splays', 'spryly', 'syllepses', 'yarely', 'yearly', 'yell', 'yeller', 'yellers',
      'yells', 'yelp', 'yelper', 'yelpers', 'yelps',
    ],
    pangrams: ['paralyse', 'paralyses', 'parleyers', 'parleys', 'parsley', 'parsleys', 'players', 'replays', 'sparely', 'sparsely']
  },
  {
    id: 10,
    letters: ['M', 'O', 'U', 'N', 'T', 'I', 'A'],
    centerLetter: 'A',
    validWords: [
      'amain', 'amanita', 'amanitin', 'amia', 'amin', 'amino', 'ammino', 'ammo',
      'ammonia', 'ammoniation', 'ammonium', 'ammono', 'ammunition', 'amnia', 'amnion', 'amotion',
      'amount', 'anatto', 'anima', 'animation', 'animato', 'animi', 'anion', 'anna',
      'annatto', 'annotation', 'annuitant', 'anoa', 'anoint', 'anon', 'anta', 'anti',
      'antiatom', 'antiman', 'antinomian', 'antiunion', 'ataman', 'atma', 'atman', 'atom',
      'attain', 'attaint', 'aunt', 'auto', 'automan', 'automata', 'automation', 'automaton',
      'autumn', 'imam', 'imaum', 'imitation', 'inanition', 'inia', 'initiation', 'intima',
      'intimation', 'intonation', 'iota', 'maim', 'main', 'maintain', 'mama', 'mamma',
      'mammati', 'mammon', 'mana', 'manana', 'mania', 'manito', 'manitou', 'manitu',
      'manna', 'mannan', 'mano', 'manta', 'mantua', 'manumit', 'matin', 'matt',
      'mattin', 'maun', 'maut', 'miaou', 'mina', 'minima', 'minutia', 'moan',
      'moat', 'momma', 'monomania', 'mountain', 'mutant', 'mutation', 'naan', 'nana',
      'naoi', 'natant', 'natation', 'nation', 'noma', 'nomina', 'nomination', 'nona',
      'nonman', 'nonmutant', 'nota', 'notation', 'numina', 'nutant', 'nutation', 'ottoman',
      'outman', 'tain', 'taint', 'tannin', 'tantamount', 'tanto', 'tatami', 'tattoo',
      'taunt', 'taut', 'tinamou', 'tinman', 'titan', 'titania', 'titanium', 'titian',
      'titman', 'toman', 'tomato', 'tuna', 'unai', 'unau', 'unman',
    ],
    pangrams: ['ammunition', 'automation', 'manitou', 'mountain', 'mutation', 'tinamou']
  },
  {
    id: 11,
    letters: ['C', 'O', 'M', 'P', 'U', 'T', 'E'],
    centerLetter: 'O',
    validWords: [
      'coco', 'cocotte', 'coempt', 'come', 'comet', 'commute', 'comp', 'compete',
      'compo', 'compote', 'compt', 'compute', 'comte', 'coocoo', 'cooee', 'coop',
      'coopt', 'coot', 'cope', 'cote', 'coup', 'coupe', 'cutout', 'emote',
      'epopee', 'memo', 'meou', 'metope', 'mome', 'moot', 'mope', 'moppet',
      'mote', 'motet', 'motmot', 'mott', 'motte', 'motto', 'moue', 'octet',
      'octette', 'otto', 'outcome', 'outcompete', 'output', 'pepo', 'petto', 'poco',
      'poem', 'poet', 'pome', 'pommee', 'pomp', 'pompom', 'poop', 'pope',
      'poppet', 'potto', 'pout', 'putout', 'putto', 'teetotum', 'tempo', 'tetotum',
      'tome', 'toom', 'toot', 'tope', 'topee', 'tote', 'totem', 'toupee',
      'tout',
    ],
    pangrams: ['compute', 'outcompete']
  },
  {
    id: 12,
    letters: ['W', 'I', 'N', 'T', 'E', 'R', 'S'],
    centerLetter: 'E',
    validWords: [
      'eerie', 'eerier', 'eeriest', 'eeriness', 'eerinesses', 'einstein', 'einsteins', 'eiswein',
      'eisweins', 'entente', 'ententes', 'enter', 'enterer', 'enterers', 'enteritis', 'enteritises',
      'enters', 'entire', 'entireness', 'entirenesses', 'entires', 'entireties', 'entities', 'entree',
      'entrees', 'entries', 'entwine', 'entwines', 'entwist', 'entwists', 'erne', 'ernes',
      'erns', 'errs', 'erses', 'erst', 'eserine', 'eserines', 'eses', 'esses',
      'ester', 'esters', 'estrin', 'estrins', 'eterne', 'eternise', 'eternises', 'eternities',
      'etwee', 'etwees', 'ewer', 'ewers', 'ewes', 'inert', 'inertness', 'inertnesses',
      'inerts', 'inner', 'inners', 'insentient', 'insert', 'inserter', 'inserters', 'inserts',
      'inset', 'insets', 'insetter', 'insetters', 'insistent', 'insister', 'insisters', 'intense',
      'intenseness', 'intensenesses', 'intenser', 'intensest', 'intensities', 'intent', 'intentness', 'intentnesses',
      'intents', 'inter', 'interest', 'interests', 'intern', 'interne', 'internee', 'internees',
      'internes', 'internist', 'internists', 'interns', 'inters', 'intertie', 'interties', 'intertwine',
      'intertwines', 'intertwist', 'intertwists', 'intestine', 'intestines', 'intine', 'intines', 'intwine',
      'intwines', 'ires', 'irises', 'iritises', 'issei', 'isseis', 'neist', 'nene',
      'nereis', 'nerts', 'ness', 'nesses', 'nest', 'nester', 'nesters', 'nests',
      'nets', 'nett', 'netter', 'netters', 'nettier', 'nettiest', 'netts', 'newer',
      'newest', 'newie', 'newies', 'newness', 'newnesses', 'news', 'newsie', 'newsier',
      'newsies', 'newsiest', 'newsiness', 'newsinesses', 'newt', 'newts', 'nine', 'nines',
      'nineteen', 'nineteens', 'nineties', 'ninnies', 'nisei', 'niseis', 'nite', 'niter',
      'niterie', 'niteries', 'niters', 'nites', 'nitre', 'nitres', 'nitrite', 'nitrites',
      'nittier', 'nittiest', 'reenter', 'reenters', 'reentries', 'rees', 'reest', 'reests',
      'rein', 'reins', 'reinsert', 'reinserts', 'reinter', 'reinters', 'reis', 'renest',
      'renests', 'renew', 'renewer', 'renewers', 'renews', 'renin', 'renins', 'renitent',
      'rennet', 'rennets', 'rennin', 'rennins', 'rent', 'rente', 'renter', 'renters',
      'rentes', 'rentier', 'rentiers', 'rents', 'rerise', 'rerisen', 'rerises', 'resee',
      'reseen', 'resees', 'resent', 'resents', 'reset', 'resets', 'resetter', 'resetters',
      'resew', 'resewn', 'resews', 'resin', 'resins', 'resist', 'resister', 'resisters',
      'resists', 'resite', 'resites', 'rest', 'rester', 'resters', 'restress', 'restresses',
      'rests', 'rete', 'retene', 'retenes', 'retest', 'retests', 'retie', 'reties',
      'retine', 'retinene', 'retinenes', 'retines', 'retinite', 'retinites', 'retinitis', 'retint',
      'retints', 'retire', 'retiree', 'retirees', 'retirer', 'retirers', 'retires', 'retries',
      'rets', 'retwist', 'retwists', 'rewet', 'rewets', 'rewin', 'rewins', 'rewire',
      'rewires', 'rewrite', 'rewriter', 'rewriters', 'rewrites', 'rewritten', 'rinse', 'rinser',
      'rinsers', 'rinses', 'rise', 'risen', 'riser', 'risers', 'rises', 'rite',
      'rites', 'ritter', 'ritters', 'seen', 'seer', 'seeress', 'seeresses', 'seers',
      'sees', 'seine', 'seiner', 'seiners', 'seines', 'seis', 'seise', 'seiser',
      'seisers', 'seises', 'seisin', 'seisins', 'sene', 'seniti', 'sennet', 'sennets',
      'sennit', 'sennits', 'sense', 'senses', 'sensitise', 'sensitises', 'sent', 'sente',
      'senti', 'sentient', 'sentients', 'sentries', 'sere', 'serein', 'sereins', 'serene',
      'sereneness', 'serenenesses', 'serener', 'serenes', 'serenest', 'serenities', 'serer', 'seres',
      'serest', 'series', 'serin', 'serine', 'serines', 'serins', 'serries', 'sers',
      'sestet', 'sestets', 'sestine', 'sestines', 'sets', 'sett', 'settee', 'settees',
      'setter', 'setters', 'setts', 'sewer', 'sewers', 'sewn', 'sews', 'sienite',
      'sienites', 'sine', 'sines', 'sinew', 'sinews', 'sinister', 'sinisterness', 'sinisternesses',
      'sinner', 'sinners', 'sinter', 'sinters', 'sire', 'siree', 'sirees', 'siren',
      'sirens', 'sires', 'sirree', 'sirrees', 'sises', 'sissier', 'sissies', 'sissiest',
      'sister', 'sisters', 'site', 'sites', 'sitten', 'sitter', 'sitters', 'sneer',
      'sneerer', 'sneerers', 'sneers', 'steer', 'steerer', 'steerers', 'steers', 'stein',
      'steins', 'stere', 'steres', 'stern', 'sterner', 'sternest', 'sternite', 'sternites',
      'sternness', 'sternnesses', 'sterns', 'stet', 'stets', 'stew', 'stews', 'sties',
      'stinter', 'stinters', 'stirrer', 'stirrers', 'street', 'streets', 'streetwise', 'stress',
      'stresses', 'strette', 'stretti', 'strew', 'strewer', 'strewers', 'strewn', 'strews',
      'sweenies', 'sweer', 'sweet', 'sweeten', 'sweetener', 'sweeteners', 'sweetens', 'sweeter',
      'sweetest', 'sweetie', 'sweeties', 'sweetness', 'sweetnesses', 'sweets', 'swine', 'swisses',
      'teen', 'teener', 'teeners', 'teenier', 'teeniest', 'teens', 'teensier', 'teensiest',
      'teentsier', 'teentsiest', 'tees', 'teeter', 'teeters', 'tenet', 'tenets', 'tenner',
      'tenners', 'tennies', 'tennis', 'tennises', 'tennist', 'tennists', 'tens', 'tense',
      'tenseness', 'tensenesses', 'tenser', 'tenses', 'tensest', 'tensities', 'tent', 'tenter',
      'tenters', 'tentie', 'tentier', 'tentiest', 'tents', 'terete', 'tern', 'terne',
      'ternes', 'terns', 'terreen', 'terreens', 'terrene', 'terrenes', 'terret', 'terrets',
      'terrier', 'terriers', 'terries', 'terrine', 'terrines', 'territ', 'territs', 'terse',
      'terseness', 'tersenesses', 'terser', 'tersest', 'test', 'testee', 'testees', 'tester',
      'testers', 'testes', 'testier', 'testiest', 'testiness', 'testinesses', 'testis', 'tests',
      'tets', 'tetter', 'tetters', 'tews', 'tier', 'tiers', 'ties', 'tine',
      'tines', 'tinier', 'tiniest', 'tininess', 'tininesses', 'tinner', 'tinners', 'tinnier',
      'tinniest', 'tinniness', 'tinninesses', 'tinter', 'tinters', 'tire', 'tires', 'titer',
      'titers', 'titre', 'titres', 'titter', 'titterer', 'titterers', 'titters', 'tittie',
      'titties', 'tree', 'treen', 'treens', 'trees', 'tress', 'tresses', 'tressier',
      'tressiest', 'tret', 'trets', 'trews', 'triene', 'trienes', 'triens', 'trientes',
      'trier', 'triers', 'tries', 'trine', 'trines', 'trinities', 'triste', 'trite',
      'triteness', 'tritenesses', 'triter', 'tritest', 'tsetse', 'tsetses', 'twee', 'tween',
      'tweenies', 'tweet', 'tweeter', 'tweeters', 'tweets', 'twenties', 'twier', 'twiers',
      'twine', 'twiner', 'twiners', 'twines', 'twinier', 'twiniest', 'twinset', 'twinsets',
      'twister', 'twisters', 'twistier', 'twistiest', 'twitter', 'twitters', 'ween', 'weenie',
      'weenier', 'weenies', 'weeniest', 'weens', 'weensier', 'weensiest', 'weer', 'wees',
      'weest', 'weet', 'weets', 'weewee', 'weewees', 'weiner', 'weiners', 'weir',
      'weirs', 'wennier', 'wenniest', 'wens', 'went', 'were', 'wert', 'west',
      'wester', 'western', 'westerner', 'westerners', 'westernise', 'westernises', 'westerns', 'westers',
      'wests', 'wetness', 'wetnesses', 'wets', 'wetter', 'wetters', 'wettest', 'wiener',
      'wieners', 'wienie', 'wienies', 'wine', 'wineries', 'wines', 'winier', 'winiest',
      'winner', 'winners', 'winter', 'winterer', 'winterers', 'winterier', 'winteriest', 'winters',
      'wintrier', 'wintriest', 'wintriness', 'wintrinesses', 'wire', 'wirer', 'wirers', 'wires',
      'wirier', 'wiriest', 'wiriness', 'wirinesses', 'wise', 'wiseness', 'wisenesses', 'wisent',
      'wisents', 'wiser', 'wises', 'wisest', 'wisses', 'wite', 'wites', 'witness',
      'witnesses', 'wittier', 'wittiest', 'wittiness', 'wittinesses', 'wren', 'wrens', 'wrest',
      'wrester', 'wresters', 'wrests', 'wrier', 'wries', 'wriest', 'wristier', 'wristiest',
      'write', 'writer', 'writers', 'writes', 'written',
    ],
    pangrams: ['intertwines', 'intertwist', 'intertwists', 'twiners', 'westernise', 'westernises', 'winterers', 'winteriest', 'winters', 'wintriest', 'wintriness', 'wintrinesses']
  },
  {
    id: 13,
    letters: ['J', 'U', 'M', 'P', 'I', 'N', 'G'],
    centerLetter: 'I',
    validWords: [
      'gigging', 'gimp', 'gimping', 'ginning', 'gipping', 'gumming', 'gunning', 'impi',
      'imping', 'impinging', 'impugn', 'impugning', 'inning', 'jigging', 'jimp', 'jinn',
      'jinni', 'jugging', 'jumping', 'migg', 'miming', 'mini', 'minim', 'minimum',
      'mining', 'minium', 'mugging', 'mumming', 'mumping', 'muni', 'nimming', 'nipping',
      'piggin', 'pigging', 'piing', 'pimp', 'pimping', 'ping', 'pinging', 'pining',
      'pinning', 'pinup', 'piping', 'pippin', 'pipping', 'pugging', 'pumping', 'punning',
      'pupping', 'umping', 'unpin', 'unpinning', 'upping',
    ],
    pangrams: ['jumping']
  },
  {
    id: 14,
    letters: ['S', 'H', 'A', 'P', 'E', 'L', 'Y'],
    centerLetter: 'A',
    validWords: [
      'aahs', 'aals', 'alae', 'alas', 'alee', 'aleph', 'alephs', 'ales',
      'allay', 'allays', 'allee', 'allees', 'allele', 'alleles', 'alley', 'alleys',
      'allheal', 'allheals', 'alls', 'ally', 'allyl', 'allyls', 'alpha', 'alphas',
      'alphyl', 'alphyls', 'alps', 'apes', 'apheses', 'aphylly', 'appal', 'appall',
      'appalls', 'appals', 'appeal', 'appeals', 'appease', 'appeases', 'appel', 'appellee',
      'appellees', 'appels', 'apple', 'apples', 'apply', 'apse', 'apses', 'asea',
      'asepses', 'ashes', 'ashless', 'ashy', 'asleep', 'asps', 'assay', 'assays',
      'asses', 'assess', 'assesses', 'asyla', 'ayah', 'ayahs', 'ayes', 'ease',
      'easel', 'easels', 'eases', 'easy', 'elapse', 'elapses', 'epha', 'ephah',
      'ephahs', 'ephas', 'essay', 'essays', 'eyas', 'eyases', 'eyelash', 'eyelashes',
      'haes', 'haha', 'hahas', 'hahs', 'halala', 'halalah', 'halalahs', 'halalas',
      'hale', 'hales', 'hall', 'hallah', 'hallahs', 'hallel', 'hallels', 'halls',
      'hapless', 'haplessly', 'haply', 'happy', 'haps', 'hash', 'hasheesh', 'hasheeshes',
      'hashes', 'hasp', 'hasps', 'hassel', 'hassels', 'hassle', 'hassles', 'hays',
      'heal', 'heals', 'heap', 'heaps', 'hyla', 'hylas', 'hypha', 'hyphae',
      'hyphal', 'lall', 'lalls', 'lapel', 'lapels', 'laps', 'lapse', 'lapses',
      'lase', 'lases', 'lash', 'lashes', 'lass', 'lasses', 'lays', 'leal',
      'leally', 'leap', 'leaps', 'leas', 'lease', 'leases', 'leash', 'leashes',
      'lyase', 'lyases', 'lyssa', 'lyssas', 'paella', 'paellas', 'pale', 'palea',
      'paleae', 'paleal', 'palely', 'pales', 'pall', 'palls', 'pally', 'palp',
      'palpal', 'palps', 'pals', 'palsy', 'paly', 'papa', 'papal', 'papally',
      'papas', 'papaya', 'papayas', 'pappy', 'paps', 'pase', 'pases', 'pash',
      'pasha', 'pashas', 'pashes', 'pass', 'passe', 'passee', 'passel', 'passels',
      'passes', 'passless', 'payee', 'payees', 'pays', 'peal', 'peals', 'peas',
      'pease', 'peases', 'pepla', 'phase', 'phaseal', 'phases', 'phyla', 'phylae',
      'plash', 'plashes', 'plashy', 'play', 'playa', 'playas', 'playless', 'plays',
      'plea', 'pleas', 'please', 'pleases', 'psylla', 'psyllas', 'pyas', 'salal',
      'salals', 'sale', 'salep', 'saleps', 'sales', 'sall', 'sally', 'salp',
      'salpa', 'salpae', 'salpas', 'salps', 'sals', 'salsa', 'salsas', 'sapless',
      'sappy', 'saps', 'sash', 'sashay', 'sashays', 'sashes', 'sass', 'sasses',
      'sassy', 'says', 'seal', 'seals', 'seas', 'seashell', 'seashells', 'selah',
      'selahs', 'sepal', 'sepals', 'shah', 'shahs', 'shale', 'shales', 'shaley',
      'shall', 'shaly', 'shape', 'shapeless', 'shapelessly', 'shapely', 'shapes', 'shay',
      'shays', 'shea', 'sheal', 'sheals', 'sheas', 'slap', 'slaphappy', 'slaps',
      'slash', 'slashes', 'slay', 'slays', 'spae', 'spaes', 'spahee', 'spahees',
      'spale', 'spales', 'spall', 'spalls', 'spas', 'spay', 'spays', 'splash',
      'splashes', 'splashy', 'splay', 'splays', 'yaps', 'yays', 'yeah', 'yeas',
    ],
    pangrams: ['haplessly', 'shapelessly', 'shapely']
  },
  {
    id: 15,
    letters: ['F', 'O', 'U', 'N', 'D', 'E', 'R'],
    centerLetter: 'U',
    validWords: [
      'defund', 'defunded', 'denude', 'denuded', 'denuder', 'dour', 'dourer', 'dude',
      'duded', 'dudeen', 'duende', 'duff', 'duffer', 'dune', 'dunned', 'dunner',
      'dure', 'dured', 'durn', 'durned', 'durneder', 'duro', 'durr', 'endue',
      'endued', 'endure', 'endured', 'enduro', 'enure', 'enured', 'euro', 'fenuron',
      'feud', 'feuded', 'feued', 'fondu', 'fondue', 'forerun', 'forerunner', 'found',
      'founded', 'founder', 'foundered', 'four', 'frondeur', 'froufrou', 'fund', 'funded',
      'funned', 'funner', 'furfur', 'furor', 'furore', 'furred', 'neuron', 'neurone',
      'noun', 'nude', 'nuder', 'nurd', 'odour', 'ordure', 'redound', 'redounded',
      'refound', 'refounded', 'refund', 'refunded', 'refunder', 'rerun', 'rondure', 'roue',
      'rouen', 'round', 'rounded', 'rounder', 'rudd', 'rudder', 'rude', 'ruder',
      'rued', 'ruer', 'ruff', 'ruffe', 'ruffed', 'rune', 'runner', 'runoff',
      'runround', 'udder', 'unde', 'undee', 'undefended', 'under', 'underdo', 'underdone',
      'underfed', 'underfeed', 'underfund', 'underfunded', 'underfur', 'underrun', 'undo', 'undoer',
      'undone', 'undue', 'unended', 'unfed', 'unfond', 'unfound', 'unfounded', 'unfree',
      'unfreed', 'unfunded', 'unneeded', 'unordered', 'unroof', 'unroofed', 'unround', 'unrounded',
      'uredo',
    ],
    pangrams: ['founder', 'foundered', 'frondeur', 'refound', 'refounded', 'unroofed']
  }

];

export function getRandomPuzzle() {
  return puzzles[Math.floor(Math.random() * puzzles.length)];
}

export function getRandomPuzzleExcluding(excludeIds = []) {
  const excluded = new Set(excludeIds.filter(Boolean));
  const pool = puzzles.filter((p) => !excluded.has(p.id));
  const source = pool.length > 0 ? pool : puzzles;
  return source[Math.floor(Math.random() * source.length)];
}

export function getPuzzleById(id) {
  return puzzles.find(p => p.id === id);
}
